
CREATE OR REPLACE FUNCTION BONUS_CALC(V_EMPID EMPLOYEE.EMP_ID%TYPE)
RETURN NUMBER
IS 
	V_SAL EMPLOYEE.SALARY%TYPE;		
	V_BONUS EMPLOYEE.BONUS%TYPE;		
	CALC_SAL NUMBER;   			              
BEGIN
	SELECT SALARY, NVL(BONUS, 0)
	INTO V_SAL, V_BONUS
	FROM EMPLOYEE
	WHERE EMP_ID = V_EMPID;

	CALC_SAL := (V_SAL + (V_SAL + V_BONUS)) * 12;
	RETURN CALC_SAL;
END;
/
SET AUTOPRINT ON;
VARIABLE VAR_CALC NUMBER;
EXEC :VAR_CALC:=BONUS_CALC('&EMP_ID');
/
